### ISSUE TITLE
Compatible with lower versions

### ISSUE THREAD

**Issue by 20030229** [project-hans/playerpersistence#4]
Do you have any idea to migrate to version 1.20.1 and lower?

**Comment by caesarakalaeii** [comment]
As the Current version is pretty bare bone, you might be able to simply change the version bindings, such as the Loom, fabric, minecraft versions and compile it yourself.
Afaik we don't use too special methods, so most versions should work, but big emphasis on should.
We currently don't plan to support older versions.
